version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: AppDB
    env_file:
    - .env
    ports:
    - 5432:5432
    volumes:
    - $HOME/db-volume:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build: .
    command: python3 flask_app.py 
    depends_on:
      postgres:
        condition: service_healthy
    ports:
    - 5000:5000
    volumes:
    - .:/app
    env_file:
    - .env
volumes:
  db-volume:
    driver: local
