apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: sashatchern/flask:v76
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: postgres-config
          env: 
            - name: DATABASE_HOST
              value: postgres   # This should match the service name for your PostgreSQL database
            - name: DATABASE_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer   # Choose the appropriate service type based on your needs
