---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pypet-deployment
  namespace: pypet-app
  labels:
    app: pypet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pypet-app
  template:
    metadata:
      labels:
        app: pypet-app
    spec:
      containers:
      - name: pypet-container
        image: sashatchern/flask-no-db:v
        ports:
        - containerPort: 5000