---
- hosts: tag_environment_flask
  become: yes

  tasks:
    - name: Update package cache
      yum:
        update_cache: yes

    - name: Install Python 3 and Pip
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - python3
        - python3-pip

    - name: Install Flask
      pip:
        name: "{{ item }}"
        state: latest
      loop:
        - flask
        - pytest

    - name: Install Apache HTTP Server (httpd)
      package:
        name: httpd
        state: latest

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install OpenSSH
      package:
        name: openssh-server
        state: latest

    - name: Install Git
      package:
        name: git
        state: latest

    - name: Install Gunicorn
      pip:
        name: gunicorn
        state: latest

    - name: Install tmux
      yum:
        name: tmux
        state: latest

    - name: Install necessary packages for docker
      dnf:
        name: dnf-plugins-core
        state: latest

    - name: Add Docker repository
      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Install Docker
      dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
